pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                git url: 'https://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@github.com/quantori/prj-bse-gpu.git', branch: 'feature/BSE-729/docker-image-creation'
                dir('docker/bse-gpu') {
                    sh "docker-compose up"
                    sh "docker-compose down"
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}