pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                git url: 'https://${env.GIT_TOKEN}@github.com/evtifievAnatoliy/saveFilesRestfullservice.git', branch: 'dev'
                sh "docker-compose up"
                sh "mvn install -DskipTests=true"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh "mvn test"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
            always {
                sh "docker-compose down"
                echo 'Temp data is deleted.'
            }
    }
}