pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                git url: 'https://github.com/evtifievAnatoliy/saveFilesRestfullservice.git', branch: 'dev'
                sh "docker-compose up"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
            always {
                sh "docker-compose down"
                echo 'Data deleted'
            }
        }
}